spring.application.name=auth-service

server.port=8080

# Active profile (configured via environment SPRING_PROFILES_ACTIVE or command-line, default is local)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# JPA common config
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ThunderMail Configuration
thundermail.api.url=https://thundermail-web-aws.vercel.app/api/v3